dist: xenial
language: go
go:
  - 1.11.6
git:
  depth: 1
notifications:
  email: false
script:
  - mkdir -p github.com/tachyon-protocol
  - mv ./ github.com/tachyon-protocol
  - go test -v -race ./...
